version: "3.3"

services:
  db-employee:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=employee
    ports:
      - 5440

  db-payment:
    image: postgres
    environment:
      - POSTGRES_USER=postgres2
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=payment
    ports:
      - 5441

  db-hookah:
    image: postgres
    environment:
      - POSTGRES_USER=postgres3
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=hookah
    ports:
      - 5442

  db-tobakko:
    image: postgres
    environment:
      - POSTGRES_USER=postgres4
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=tobakko
    ports:
      - 5443

  tobakko-service:
    build: tobakko-service/
    ports:
      - "8081:8081"
    depends_on:
      - db-tobakko

  employee-service:
    build: employee-service/
    ports:
      - "8082:8082"
    depends_on:
      - db-employee

  payment-service:
    build: payment-service/
    ports:
      - "8083:8083"
    depends_on:
      - db-payment

  hookah-service:
    build: hookah-service/
    ports:
      - "8084:8084"
    depends_on:
      - db-hookah

  mediator:
    build: mediator/
    ports:
      - "8080:8080"
    depends_on:
      - tobakko-service
      - employee-service
      - payment-service
      - hookah-service
