apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-employee
  template:
    metadata:
      labels:
        app: db-employee
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: employee
        - name: POSTGRES_PASSWORD
          value: "123"
        - name: POSTGRES_USER
          value: postgres
        image: postgres
        imagePullPolicy: IfNotPresent
        name: db-employee
        ports:
        - containerPort: 5432