apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: db-hookah
  name: db-hookah
spec:
  ports:
  - name: "db-hookah"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: db-hookah
status:
  loadBalancer: {}