apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-hookah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-hookah
  template:
    metadata:
      labels:
        app: db-hookah
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: hookah
        - name: POSTGRES_PASSWORD
          value: "123"
        - name: POSTGRES_USER
          value: postgres3
        image: postgres
        imagePullPolicy: IfNotPresent
        name: db-hookah
        ports:
        - containerPort: 5432