apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-payment
  template:
    metadata:
      labels:
        app: db-payment
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: payment
        - name: POSTGRES_PASSWORD
          value: "123"
        - name: POSTGRES_USER
          value: postgres2
        image: postgres
        imagePullPolicy: IfNotPresent
        name: db-payment
        ports:
        - containerPort: 5432
