apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-tobakko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-tobakko
  template:
    metadata:
      labels:
        app: db-tobakko
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: tobakko
        - name: POSTGRES_PASSWORD
          value: "123"
        - name: POSTGRES_USER
          value: postgres4
        image: postgres
        imagePullPolicy: IfNotPresent
        name: db-tobakko
        ports:
        - containerPort: 5432
