apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: db-tobakko
  name: db-tobakko
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-tobakko
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: db-tobakko
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: tobakko
        - name: POSTGRES_PASSWORD
          value: "123"
        - name: POSTGRES_USER
          value: postgres4
        image: postgres
        imagePullPolicy: ""
        name: db-tobakko
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
