apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hookah-service
  name: hookah-service
spec:
  ports:
  - name: "hookah-service"
    port: 8084
    targetPort: 8084
  selector:
    io.kompose.service: hookah-service
status:
  loadBalancer: {} 