apiVersion: apps/v1
kind: Deployment
metadata:
  name: hookah-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hookah-service
  template:
    metadata:
      labels:
        app: hookah-service
    spec:
      containers:
      - image: hookah-shop-3_hookah-service
        imagePullPolicy: IfNotPresent
        name: hookah-service
        ports:
        - containerPort: 8084