apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  ports:
  - name: "payment-service"
    port: 8083
    targetPort: 8083
  selector:
    io.kompose.service: payment-service