apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: tobakko-service
  name: tobakko-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tobakko-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: tobakko-service
    spec:
      containers:
      - image: hookah-shop-3_tobakko-service
        name: tobakko-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}