apiVersion: apps/v1
kind: Deployment
metadata:
  name: tobakko-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tobakko-service
  template:
    metadata:
      labels:
        app: tobakko-service
    spec:
      containers:
      - image: hookah-shop-3_tobakko-service
        name: tobakko-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081